//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HistoryClient.SimpleService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SimpleService.SimpleSoap")]
    public interface SimpleSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        HistoryClient.SimpleService.HelloWorldResponse HelloWorld(HistoryClient.SimpleService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<HistoryClient.SimpleService.HelloWorldResponse> HelloWorldAsync(HistoryClient.SimpleService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name FoolinResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Foolin", ReplyAction="*")]
        HistoryClient.SimpleService.FoolinResponse Foolin(HistoryClient.SimpleService.FoolinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Foolin", ReplyAction="*")]
        System.Threading.Tasks.Task<HistoryClient.SimpleService.FoolinResponse> FoolinAsync(HistoryClient.SimpleService.FoolinRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public HistoryClient.SimpleService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(HistoryClient.SimpleService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public HistoryClient.SimpleService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(HistoryClient.SimpleService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FoolinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Foolin", Namespace="http://tempuri.org/", Order=0)]
        public HistoryClient.SimpleService.FoolinRequestBody Body;
        
        public FoolinRequest() {
        }
        
        public FoolinRequest(HistoryClient.SimpleService.FoolinRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FoolinRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int a;
        
        public FoolinRequestBody() {
        }
        
        public FoolinRequestBody(int a) {
            this.a = a;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FoolinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FoolinResponse", Namespace="http://tempuri.org/", Order=0)]
        public HistoryClient.SimpleService.FoolinResponseBody Body;
        
        public FoolinResponse() {
        }
        
        public FoolinResponse(HistoryClient.SimpleService.FoolinResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FoolinResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FoolinResult;
        
        public FoolinResponseBody() {
        }
        
        public FoolinResponseBody(string FoolinResult) {
            this.FoolinResult = FoolinResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SimpleSoapChannel : HistoryClient.SimpleService.SimpleSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimpleSoapClient : System.ServiceModel.ClientBase<HistoryClient.SimpleService.SimpleSoap>, HistoryClient.SimpleService.SimpleSoap {
        
        public SimpleSoapClient() {
        }
        
        public SimpleSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimpleSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HistoryClient.SimpleService.HelloWorldResponse HistoryClient.SimpleService.SimpleSoap.HelloWorld(HistoryClient.SimpleService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            HistoryClient.SimpleService.HelloWorldRequest inValue = new HistoryClient.SimpleService.HelloWorldRequest();
            inValue.Body = new HistoryClient.SimpleService.HelloWorldRequestBody();
            HistoryClient.SimpleService.HelloWorldResponse retVal = ((HistoryClient.SimpleService.SimpleSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HistoryClient.SimpleService.HelloWorldResponse> HistoryClient.SimpleService.SimpleSoap.HelloWorldAsync(HistoryClient.SimpleService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<HistoryClient.SimpleService.HelloWorldResponse> HelloWorldAsync() {
            HistoryClient.SimpleService.HelloWorldRequest inValue = new HistoryClient.SimpleService.HelloWorldRequest();
            inValue.Body = new HistoryClient.SimpleService.HelloWorldRequestBody();
            return ((HistoryClient.SimpleService.SimpleSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HistoryClient.SimpleService.FoolinResponse HistoryClient.SimpleService.SimpleSoap.Foolin(HistoryClient.SimpleService.FoolinRequest request) {
            return base.Channel.Foolin(request);
        }
        
        public string Foolin(int a) {
            HistoryClient.SimpleService.FoolinRequest inValue = new HistoryClient.SimpleService.FoolinRequest();
            inValue.Body = new HistoryClient.SimpleService.FoolinRequestBody();
            inValue.Body.a = a;
            HistoryClient.SimpleService.FoolinResponse retVal = ((HistoryClient.SimpleService.SimpleSoap)(this)).Foolin(inValue);
            return retVal.Body.FoolinResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HistoryClient.SimpleService.FoolinResponse> HistoryClient.SimpleService.SimpleSoap.FoolinAsync(HistoryClient.SimpleService.FoolinRequest request) {
            return base.Channel.FoolinAsync(request);
        }
        
        public System.Threading.Tasks.Task<HistoryClient.SimpleService.FoolinResponse> FoolinAsync(int a) {
            HistoryClient.SimpleService.FoolinRequest inValue = new HistoryClient.SimpleService.FoolinRequest();
            inValue.Body = new HistoryClient.SimpleService.FoolinRequestBody();
            inValue.Body.a = a;
            return ((HistoryClient.SimpleService.SimpleSoap)(this)).FoolinAsync(inValue);
        }
    }
}
