//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HistoryClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photoinfo
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date___Time { get; set; }
        public string Situation { get; set; }
        public Nullable<bool> Happy { get; set; }
        public Nullable<bool> Sad { get; set; }
        public Nullable<bool> Angry { get; set; }
        public Nullable<bool> Confused { get; set; }
        public Nullable<bool> Disgusted { get; set; }
        public Nullable<bool> Suprised { get; set; }
        public Nullable<bool> Calm { get; set; }
        public Nullable<bool> Fear { get; set; }
        public Nullable<bool> Unknown { get; set; }
        public byte[] Photo { get; set; }

        public Photoinfo(Info info, Byte[] photo)
        {
            this.Date___Time = DateTime.Now;
            this.Situation = info.eventName;
            this.Photo = photo;

            Emotion emotions = info.emotion;
            if (emotions == 0)
            {
                this.Unknown = true;
            } else
            {
                this.Unknown = false;
            }

            this.Happy = emotions.HasFlag(Emotion.HAPPY);
            this.Sad = emotions.HasFlag(Emotion.SAD);
            this.Angry = emotions.HasFlag(Emotion.ANGRY);
            this.Confused = emotions.HasFlag(Emotion.CONFUSED);
            this.Suprised = emotions.HasFlag(Emotion.SURPRISED);
            this.Calm = emotions.HasFlag(Emotion.CALM);
            this.Fear = emotions.HasFlag(Emotion.FEAR);
            this.Disgusted = emotions.HasFlag(Emotion.DISGUSTED);
        }
    }

}
